### ISSUE TITLE
所有模型都准备好了，运行infer.py时报错

### ISSUE THREAD

**Issue by mjmjmmmjjj** [LinkSoul-AI/LLaSM#5]
命令：python infer.py --input_audio_file d:/tmp/output.wav --llasm_model F:/models/LLaSM-Cllama2 --llasm_audio_tower F:/models/whisper-medium --llm_type "Chinese_llama2"
报错：RuntimeError: mat1 and mat2 shapes cannot be multiplied (64x1024 and 1280x4096)

是哪里的问题？求解答，谢谢！~

**Comment by mjmjmmmjjj** [comment]
模型加载环节都没有问题，是.wav文件问题？还是模型的问题？

**Comment by TabbbSY** [comment]
Please use the Whisper large v2 model instead. Download from https://huggingface.co/openai/whisper-large-v2
